### ISSUE TITLE
deadlock on ctrl-c

### ISSUE THREAD

**Issue by emiltin** [socketry/async#45] opened 2019-08-14 13:47 UTC
I sometimes get "deadlock; recursive locking (ThreadError)" on ctrl-c in the terminal. I'm on MacOS 10.14.6.

```
Emils-iMac:rsmp emiltin$ ruby ignore/test.rb 
^CTraceback (most recent call last):
	6: from ignore/test.rb:3:in `<main>'
	5: from /Users/emiltin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/async-1.20.1/lib/async.rb:34:in `Async'
	4: from /Users/emiltin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/async-1.20.1/lib/async/reactor.rb:56:in `run'
	3: from /Users/emiltin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/async-1.20.1/lib/async/reactor.rb:56:in `ensure in run'
	2: from /Users/emiltin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/async-1.20.1/lib/async/reactor.rb:226:in `close'
	1: from /Users/emiltin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/async-1.20.1/lib/async/reactor.rb:226:in `close'
/Users/emiltin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/async-1.20.1/lib/async/reactor.rb:226:in `lock': deadlock; recursive locking (ThreadError)

Emils-iMac:rsmp emiltin$ cat ignore/test.rb
require 'async'

Async do |task|
  task.async do |subtask|
    subtask.sleep 100
  end
end

Emils-iMac:rsmp emiltin$ gem list async

*** LOCAL GEMS ***

async (1.20.1)
async-await (0.3.0)
async-io (1.24.0)
async-rspec (1.13.0)

Emils-iMac:rsmp emiltin$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
```

**Comment by ioquatix** [comment] 2019-08-14 20:25
It's a bug with Ruby 2.5

I don't know if it was fixed in 2.6, but the issue should be fixed in 2.7.

Can you try 2.6 and see if it's more reliable?

**Comment by bryanp** [comment] 2019-08-14 22:57
FWIW I still encounter this on 2.6.3p62. Hopefully fixed in 2.7!

**Comment by ioquatix** [comment] 2019-08-14 23:00
https://bugs.ruby-lang.org/issues/15360

**Comment by ioquatix** [comment] 2019-08-14 23:02
I'm going to close this issue but please do report back your experiences, good to know if the problem is still happening in 2.7 for example.

**Closed** 2019-08-14 23:04 UTC

**Comment by emiltin** [comment] 2019-08-15 11:50
so far I haven't seen this with ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
