### ISSUE TITLE
transient task behaviour?

### ISSUE THREAD

**Issue by emiltin** [socketry/async#179] opened 2022-09-08 14:10 UTC
Hi,
My understanding of using transient:true is that any child task will be terminated as soon as the parent task ends.

But I don't understand this:
```ruby
require 'async'
Async(transient: true) do |task|
  task.sleep 10000
end.wait
puts "done"
```
Which immediately prints "done" for both async 1.30.3 and 2.1. Why does wait() have no effect here?

**Comment by emiltin** [comment] 2022-09-08 14:13
Or just:
```ruby
require 'async'
Async(transient: true) do |task|
  task.sleep 10000
end
puts "done"
```
Which also immediately prints "done".

**Comment by ioquatix** [comment] 2022-09-08 21:32
Transient tasks do not keep the reactor alive, so IIUC, it's exiting after the first iteration of the event loop because it's considered finished.

**Comment by emiltin** [comment] 2022-09-09 08:06
OK I see.
My use case is that I want to run a task that uses some background child tasks. Once the main task completes, I want all childs (and grand childs) to be stopped immediately. Maybe the parent task can call stop on itself?

**Comment by ioquatix** [comment] 2022-09-09 11:17
Can you make the background tasks transient?

**Comment by emiltin** [comment] 2022-09-09 13:07
Yes I can make the background task transient, at least by wrapping them in a. transient task.

> Transient tasks do not keep the reactor alive, so IIUC, it's exiting after the first iteration of the event loop because it's considered finished.

I think this is what I don't understand. If the task `task.sleep 10000` why is it immediately considered finished? 
So in the example above, why does it immediately print 'done'?

Do they need a parent task that's not completed, to keep then running?

**Comment by ioquatix** [comment] 2022-09-10 06:40
Thanks for your questions. I'll try my best to answer it, but if it's not clear keep on asking.

Transient tasks do not keep the reactor alive even if they are busy, they will be stopped forcefully. This is by design. If you don't expect/want that behaviour, don't make transient tasks.

<img width="660" alt="image" src="https://user-images.githubusercontent.com/30030/189471758-1d2195b3-8f30-4264-8aed-882e54df9b28.png">

https://github.com/socketry/async/blob/442d242efc1a8ec994b9520c938bf3efe4c6f141/lib/async/node.rb#L138-L140 is true when there are only transient children. When this is true at the top level, reactor will exit. Exiting the reactor will terminate all remaining tasks.

Transient tasks let you have behaviour scoped to the life of the reactor, which isn't always the same as lexical/stack scope. This is very useful for implementing caches and other things which should be cleaned up when the reactor exits (e.g. connection pools, etc).

**Comment by emiltin** [comment] 2022-09-16 07:24
Thank you for the clear explanation.

I'm using this for RSpec testing of a tcp servers/clients. The server and the client normally run until stopped. For testing, I want to start them, then run some tests by communicating with them, and then make sure the client/server and all their possible subtask are terminated. That's why I looked running the server/cleint inside a transient task.

But if I use a transient task, the tests will sometimes fail due to timeouts when waiting for the server/client to reach specific states. If I don't use a transient task, but instead run the server/client in normal task, which I manually stop(), then tests always succeed.

It's not clear to me whether this is expected behaviour.

```ruby
# always works
Async do |task|
    Async do |transient|
      # open a tcp server
    end
  end
  # read/write to server using Async::IO classes
  # use Async::Notification to wait for the server reaching certain states
ensure
  task.stop
end


# sometimes times out
Async do |task|
    Async transient: true do |transient|
      # run a tcp server
    end
  end
  # read/write to server using Async::IO classes
  # use Async::Notification to wait for the server reaching certain states - timeouts sometimes happen
end
```


The timeouts seems a bit random, and seems to happen on both Mac, Linux and Windows. The server and client both has a reader in a child task, and the server listens for connections, etc. so there's a bit of code involved.

https://github.com/rsmp-nordic/rsmp/actions/runs/3060194417/attempts/2

**Comment by ioquatix** [comment] 2022-09-16 07:30
Can you please double check the code example formatting is correct? It might be missing a line or have an extra `end`.

**Comment by emiltin** [comment] 2022-09-16 10:09
Ah sorry. Fixed.

**Comment by ioquatix** [comment] 2022-09-16 23:30
In the 2nd case, is it true that the `Async do |task|` is the top level task? Otherwise, you can leak the transient task. In the first example, you are calling `task.stop` which will stop all children, but in the 2nd you aren't, if you have an outer async block, the transient task will re-parent.

```
Async do
  Async do |task|
    Async transient: true do |transient|
      # run a tcp server
    end
    # read/write to server using Async::IO classes
    # use Async::Notification to wait for the server reaching certain states
  end
  
  # Transient task may still exist here.
end
```

**Comment by ioquatix** [comment] 2022-11-02 07:22
I've written about this more in the documentation: https://socketry.github.io/async/guides/asynchronous-tasks/index.html#transient-tasks

**Comment by ioquatix** [comment] 2023-06-07 11:45
I'm going to close this issue. Please feel free to create a discussion if you have further questions.

https://github.com/socketry/async/discussions

**Closed by ioquatix** 2023-06-07 11:45 UTC
